[project]
name    = "Jank"
version = "0.1.0"

description = "Oi, janky hack mate!"

min_janky_version = "0.1.0"

c_standard   = 11
cxx_standard = 17

# TODO exclude build sources by target, but still show them in generated xcode/vs projects

[targets.JankEngine]
type = "Application"

assets  = "assets"
sources = ["engine/**/*",
           # "external/fmt/include/fmt/*.h",
           # "external/fmt/src/*.cc",
           "external/imgui/*.h",
           "external/imgui/*.cpp",
           "external/Box2D/Box2D/**/*"
           ]

include_dirs = ["external/EGL-Registry/api",
                "external/OpenGL-Registry/api",
                "external/Box2D",
                # "external/chibi-scheme/include"
                ]

[targets.JankEngine.filters]
"engine/app/android" = ["Android"]
"engine/app/apple"   = ["MacOS", "IOS", "TVOS"]
"engine/app/html5"   = ["HTML5"]
"engine/app/linux"   = ["Linux"]
"engine/app/windows" = ["Windows"]

"engine/audio/coreaudio" = ["MacOS", "IOS", "TVOS"]
"engine/audio/openal"    = ["Linux", "Android", "HTML5"]
"engine/audio/xaudio"    = ["Windows"]

"engine/gfx/d3d12"  = ["Windows"]
"engine/gfx/metal"  = ["MacOS", "IOS", "TVOS"]
"engine/gfx/vulkan" = ["Android", "Windows", "Linux"]

# TODO make editor depend on engine; reuse sources
[targets.JankEditor]
type = "Application"

depends   = ["JankEngine"]
platforms = ["Linux", "MacOS", "Windows"]
defines   = ["BUILD_EDITOR"]

assets  = "assets"
sources = ["editor/**/*"]
