[project]
name    = "Jank"
version = "0.1.0"

description = "Oi, janky hack mate!"

min_janky_version = "0.1.0"

c_standard   = 11
cxx_standard = 17

[targets.JankEngine]
type = "Application"

assets  = "assets"
sources = ["engine/**/*",
           # "external/fmt/include/fmt/*.h",
           # "external/fmt/src/*.cc",
           "external/imgui/*.h",
           "external/imgui/*.cpp",
           "external/Box2D/Box2D/**/*"
           ]

include_dirs = ["engine",
                "external/EGL-Registry/api",
                "external/OpenGL-Registry/api",
                "external/rtm/includes",
                "external/concurrentqueue",
                "external/imgui",
                "external/Box2D",
                # "external/chibi-scheme/include"
                ]

[targets.JankEngine.filters]
"engine/app/android" = ["Android"]
"engine/app/apple"   = ["MacOS", "IOS", "TVOS"]
"engine/app/html5"   = ["HTML5"]
"engine/app/linux"   = ["Linux"]
"engine/app/windows" = ["Windows"]

"engine/audio/coreaudio" = ["MacOS", "IOS", "TVOS"]
"engine/audio/openal"    = ["Linux", "Android", "HTML5"]
"engine/audio/xaudio2"   = ["Windows"]

"engine/gfx/d3d11"  = ["Windows"]
"engine/gfx/d3d12"  = ["Windows"]
"engine/gfx/metal"  = ["MacOS", "IOS", "TVOS"]
"engine/gfx/vulkan" = ["Android", "Windows", "Linux"]

[targets.JankEditor]
type = "Application"

extends   = ["JankEngine"]
platforms = ["Linux", "MacOS", "Windows"]
defines   = ["BUILD_EDITOR=1"]

assets  = "assets"
sources = ["editor/**/*"]

include_dirs = ["editor",
                "external/assimp/include",
                "external/stb",
                "external/Compressonator/Compressonator/Header",
                ]

libs = ["assimp", "IrrXML", "zlib", "Compressonator"]
